name: JumpRandomizer
version: '${version}'
main: me.leandecks.jumprandomizer.JumpRandomizer
api-version: '1.20'
authors: [Leandecks]
description: Random mob spawns every time you jump
website: https://leandecks.github.io/

commands:
  jumprandomizer:
    description: "Random mob spawns every time you jump"
    usage: /<command>